
# This is a file for you to write an un-named query.
# Only one un-named query is allowed per file.
query {
  skills{
    author {
      clerkId
      email
      unsername
      imageUrl
    }
    title
    description
    tags
    installCommand
    promtConfig
    usageExample
    createdAt
  }
}